### ISSUE TITLE
"No valid header" issue

### ISSUE THREAD

**Issue by deskroid** [vimes1984/woocommerce_simple_tickets#1]
Hey,

Just tried to install the plugin and saw this error:

"The plugin does not have a valid header."

Can you help?

I am on latest versions of WooCommerce and WordPress.

Thanks in advance.

**Comment by vimes1984** [comment]
how did you install it via the plugin finder on the backend of wordpress, or ftp?

**Comment by deskroid** [comment]
Hey. I installed it via the WordPress dashboard's Upload Plugin option.

**Comment by vimes1984** [comment]
try ftp. I've just tested it here on a clean install and it seems to work
fine

**Comment by deskroid** [comment]
Ok. I will let you know how that goes.

— 
Regards,
Yuvraj Vaghela
