### ISSUE TITLE
Problems with tracking

### ISSUE THREAD

**Issue by ultimateairsoft** [vimes1984/woocommerce_simple_tickets#3]
hi there, ive installed this plugin and it does exactly what i need it to do however i have no way to follow what ticket has been purchased. for example i buy a ticket and my ticket number is 123456, on the back end i can not see what you got so it leaves room for people to generate their own numbers and i have no way to verify this. 

currently i can only track the sale of the item versus any redemption. but this is a blind method and time consuming.

Please help

**Comment by vimes1984** [comment]
ummm If i Remember correctly the ticket number is generated like so : 
Orderid + product ID + Number of item bought in purchase.
If  you want to add to this please feel free this is a open source project :D 
https://github.com/vimes1984/woocommerce_simple_tickets/blob/master/includes/Class_emails.php
Line 174 of the above mentioned file is what adds the ticket id to the bottom of the ticket :dancer: 
' $pdf->Cell(0, 10, 'Ticket id: ' .  $this->object->id .'' .$value['product_id'] .''.$x , 0, 0, 'C');'

**Comment by ultimateairsoft** [comment]
Hi Christopher,

Thanks for the quick reply. My issue isn’t about generating the code, it does that fine. My concern is that i have no way to track what has been generated. Pic attached shows the front end works. Just i have no way to know what code was issued

Thank you

stefano

**Comment by vimes1984** [comment]
I'm saying you can cross reference the code because it's the Purchase ID + the ITEM ID + Number of ITem the Purchase if is always unique go to your purchases in the backend and you'll seem them there.,.

**Comment by ultimateairsoft** [comment]
Thank you Christopher it all worked out! A++

Stefano

**Comment by vimes1984** [comment]
HAHAHA,no worries mate. If you want to leave a review on wordpress:
https://wordpress.org/support/view/plugin-reviews/woocommerce-simple-tickets
It'd help a lot !
Chris
